steps:
- id: build
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/infiniteblocks/website:${SHORT_SHA} .
    docker push ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/infiniteblocks/website:${SHORT_SHA}

- id: deploy
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args:
  - '-c'
  - |
      echo "***************************"
      echo "DEPLOY MAIN"
      echo "***************************"
      gcloud deploy releases create ifb-webapp-release-${SHORT_SHA} \
      --delivery-pipeline=infiniteblocks-delivery-pipeline \
      --region=europe-west1 \
      --to-target=ifb-webapp-staging \
      --images app=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/infiniteblocks/website:${SHORT_SHA}


options:
  logging: CLOUD_LOGGING_ONLY