apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ifb-webapp
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 148982833099-compute@developer.gserviceaccount.com
      containers:
      - name: ifb
        image: app
        ports:
        - name: http1
          containerPort: 3000
        # TODO env:
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000